package com.learning.photoshow.core.routers

const val LISTING_PHOTOS_ROUTER = "LISTING_PHOTOS_ROUTER"
const val VIEWING_PHOTO_ROUTER = "VIEWING_PHOTO_ROUTER"
const val MAIN_SCREEN_ROUTER = "MAIN_SCREEN_ROUTER"